### ISSUE TITLE
Batch conversion

### ISSUE THREAD

**Issue by vbguyny** [micheldebree/retropixels#51]
This is an amazing utility and I use it to create my own custom "Nuvies" (https://www.youtube.com/watch?v=b2pP2DoG93E), however, it takes a while to create the KLA file for each frame and I was wondering there could be a batch option implemented where it takes a folder of PNG files and automatically creates the related KLA files?  Thanks!

**Comment by micheldebree** [comment]
Thanks @vbguyny. I have a batch processing script for "c64-ifying" movies: https://github.com/micheldebree/retroframes

With some hacking this could be made into what you need. It works like this:
- extracts the frames of a movie to PNG
- runs the PNG frames through retropixels
- combines the converted PNGs back into a movie
- adds the original audio

If you are comfortable with developing, you could have a look how it works and adapt it to output .kla files in the second step and skip the rest. Let me know if you need any help.
