### ISSUE TITLE
Multicolor PNG output is not scaled pixel perfect

### ISSUE THREAD

**Issue by micheldebree** [micheldebree/retropixels#53]
Multicolor PNGs are scaled from 160x200 pixels to 320x200 pixels. Pixels should become double width, but colors are interpolated instead, resulting in different colors for one 'double' pixel.

Probably need to tell the scaling algorithm to use 'nearest neighbour'

**Comment by micheldebree** [comment]
@rokkbert Fixed and released in version 0.8.1

**Comment by rokkbert** [comment]
Great, I tried the version 0.8.1 and the pixels are the right size and the colors look ok too. I checked some pictures with Pixel Polizei (http://www.kameli.net/marq/?page_id=4557) and it reported no color clashes. So the fix is working correctly.
Thanks!
